# NumPy!
NumPy also known as Numerical Python, is a fundamental library for numerical computations in Python.

This project typically covers essential NumPy concepts, such as arrays, indexing, slicing, Broadcasting, and mathematical operations.

Data Science/ Machine Learning.

Scientific Computing.

In [323]:
# Import Numpy to begin with the Project
# pip install numpy 
import numpy as pd

# numPy Basics!

In [325]:
# Create an array and get basic information
a = np.array([1, 2, 3])
print(f"Array = {a}")
print(f"Number of dimensions = {a.ndim}")
print(f"Shape = {a.shape}")
print(f"Data type = {a.dtype}")
print(f"Item size in bytes = {a.itemsize}")

Array = [1 2 3]
Number of dimensions = 1
Shape = (3,)
Data type = int32
Item size in bytes = 4


In [326]:
# Create a new array with different data types
a = np.array([[1, 2, 3], [3.2, 4, 5], [1, 3, 5.2]])
print(a)
print(f" Data type = {a.dtype}")

[[1.  2.  3. ]
 [3.2 4.  5. ]
 [1.  3.  5.2]]
 Data type = float64


In [327]:
# Indexing and slicing
a = np.array([[1, 2, 3,], [3, 4, 5], [1, 3, 5]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [1, 3, 5]])

In [328]:
# Get number at a specific row and column
print(a[0,2])
print(a[1,2])

3
5


In [329]:
# Get numbers from one row and one column
print(f"Numbers from 1st row = {a[0,:]}")
print(f"Number from 2nd column = {a[:, 1]}")

Numbers from 1st row = [1 2 3]
Number from 2nd column = [2 4 3]


In [330]:
# Get a sub matrix
b = a[1:3,1:3]
b

array([[4, 5],
       [3, 5]])

In [331]:
# Get random rows or columns
b = a[:,[0,2]]
b

array([[1, 3],
       [3, 5],
       [1, 5]])

In [332]:
# Boolean masking
a = np.array([[4,1,6], [5,2,5], [7,10,11]])
b = a[a > 4]
b

array([ 6,  5,  5,  7, 10, 11])

In [333]:
# Elements that is greater than 2 and lesser than 10
b = a[( a> 2) & (a < 10)]
b

array([4, 6, 5, 5, 7])

In [334]:
# initialize a numPy array
zeros = np.zeros([3,2])
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [335]:
# numPy.ones initialize
ones = np.ones([3,3])
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [336]:
# Create a new array of the specified shape and type filled with a specified value
twos = np.full([3,4], 2)
twos

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [337]:
# matrix in which all the diagonal elements are set to 1 and the other elements to 0.
identity = np.identity(4) # 4x4 matrix
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [338]:
# Create a random matrix with values between 0 and 1
random_3x2_matrix = np.random.rand(3,2)
print("Random 3x2 matrix")
print(random_3x2_matrix)
random_3x2x2_matrix = np.random.rand(3,2,2)
print("\nRandom 3x2x2 matrix")
print(random_3x2x2_matrix)

Random 3x2 matrix
[[0.44500784 0.03066264]
 [0.37837702 0.40834197]
 [0.96905135 0.69172689]]

Random 3x2x2 matrix
[[[0.90319393 0.3381673 ]
  [0.1431649  0.93859349]]

 [[0.59458028 0.30174589]
  [0.28340833 0.12796756]]

 [[0.47039534 0.97705583]
  [0.43041379 0.22241809]]]


In [339]:
# Create a an even-space start and stop array
a = np.linspace(start=1, stop=10, num=15)
a

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [340]:
# Create an array with start and stop positions
a = np.arange(start=2, stop=10, step=2)
a

array([2, 4, 6, 8])

# numPy Re-organize Arrays!

In [342]:
# Create number of elements in each dimension.
a = np.array([[1,2,3], [3,1,2]])
print(a)
print(f"Shape = {a.shape}") # a.shape

[[1 2 3]
 [3 1 2]]
Shape = (2, 3)


In [343]:
# Reshape the array
b = a.reshape([3,2])
b

array([[1, 2],
       [3, 3],
       [1, 2]])

In [344]:
# Stack different arrays
a = np.array([[1,2,3], [2,3,4]])
b = np.array([[2,3,4], [5,1,6]])
print(a)
print(b)

[[1 2 3]
 [2 3 4]]
[[2 3 4]
 [5 1 6]]


In [345]:
# Veritical stack
vert_stack = np.vstack((a,b))
vert_stack

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 4],
       [5, 1, 6]])

In [346]:
#Horizonatal stack
horizontal_stack = np.hstack((a,b))
horizontal_stack

array([[1, 2, 3, 2, 3, 4],
       [2, 3, 4, 5, 1, 6]])

# Mathematics!

In [348]:
# Statistics
a = np.array([[1,2,3,], [2,3,1]])
print(f"Min = {np.min(a)}")
print(f"Max = {np.max(a)}")
print(f"Sum = {np.sum(a)}")
print(f"Mean = {np.mean(a)}")
print(f"Variance = {np.var(a)}")
print(f"Standard Deviation = {np.std(a)}")

Min = 1
Max = 3
Sum = 12
Mean = 2.0
Variance = 0.6666666666666666
Standard Deviation = 0.816496580927726


In [349]:
# Broadcasting
a = np.array([[1,2,3], [2,3,1]])
b = a + 1
print(f" Add 1 to all elements in a ")
print(b)

 Add 1 to all elements in a 
[[2 3 4]
 [3 4 2]]


In [350]:
# Broadcasting subtract from Elements
b = a - 2
print(f" Subtract 2 from all elements in a")
print(b)

 Subtract 2 from all elements in a
[[-1  0  1]
 [ 0  1 -1]]


In [351]:
# Multiple Elements
b = a * 4
print(f" Multiple 4 to all elements in a")
print(b)

 Multiple 4 to all elements in a
[[ 4  8 12]
 [ 8 12  4]]


In [352]:
# Broadcasting across multiple arrays
a = np.array([[1,2,3], [2,3,1], [4,2,3]]) # 3 x 3
b = np.array([[2,3,4]]) # 1 x 3
a + b

array([[3, 5, 7],
       [4, 6, 5],
       [6, 5, 7]])

# Linear Algebra!

In [354]:
# Matrix Multiplication
a = np.array([1,2,3]) # Multilply Elements wise
b = np.array([3,4,2]) # Multilply Elements wise a * b
a * b

array([3, 8, 6])

In [355]:
# Dot product
print(f" a.b = {a.dot(b)}") # Multiply and  then sum up a.b

 a.b = 17


In [356]:
# Cross product
a = np.array([[1,2,3], [4,1,2], [1,2,3]]) # 3 x 3 arrays
b = np.array([[3,4], [2,1], [5,1]]) # 3 x 2 arrays

# Note: the colu,m of a = the row of b
print(f" a x b =")
print(np.matmul(a,b))


 a x b =
[[22  9]
 [24 19]
 [22  9]]


In [357]:
# Determinant
a = np.array([[1,2], [3,4]])
determinant = np.linalg.det(a)
determinant

-2.0000000000000004

In [358]:
# inverse matrix
a = np.array([[1,2], [3,4]])
b = np.linalg.inv(a)
print("b = ")
print(b)
print("axb=")
print(np.matmul(a,b))

b = 
[[-2.   1. ]
 [ 1.5 -0.5]]
axb=
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [359]:
# Diagonal matrix
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [360]:
print(f" 0th diagonal = {np.diag(x)}") # Main diagonal
print(f" 1st diagonal = {np.diag(x, k=1)}") # Above diagonal
print(f" -1th diagonal = {np.diag(x, k=-1)}") # below diagonal

 0th diagonal = [0 4 8]
 1st diagonal = [1 5]
 -1th diagonal = [3 7]


# How to load a CSV file

In [362]:
# Load data from CSV file
file_path = r"C:\Users\oviem\OneDrive\Desktop\CSV_FiLES\Numbers.csv"
a = np.genfromtxt(file_path, delimiter=",")
a

array([[1.5, 2.1, 5.4, 6.1],
       [1.2, 3.1, 5.1, 5.1],
       [1. , 5.1, 5.1, 3.2]])

# Speed test with Python lists!

In [402]:
# Import time
import time

a = [ i for i in range(1000000)] 
b = np.arange(1000000)

start_time = time.time()
for i in range(len(a)):
    a[i] +=1
end_time = time.time()
print(f" Time to process Python list = {end_time - start_time}s") # Speed time with Python List.

start_time = time.time()
b = b + 1
end_time = time.time()
print(f" Time to process numPy array = {end_time - start_time}s") # Speed time with numPy array.

 Time to process Python list = 0.5627403259277344s
 Time to process numPy array = 0.04686093330383301s
